# vich_uploader:
#     db_driver: orm

#     mappings:
#         Upload:
#               uri_prefix: /files/Upload
#               upload_destination: '%kernel.project_dir%/public/files/Upload'
#               namer: Vich\UploaderBundle\Naming\UniqidNamer