<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQkReDWr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQkReDWr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQkReDWr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQkReDWr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQkReDWr\App_KernelDevDebugContainer([
    'container.build_hash' => 'QkReDWr',
    'container.build_id' => 'b86adfd3',
    'container.build_time' => 1654695202,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQkReDWr');
