<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAcOgcAF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAcOgcAF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAcOgcAF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAcOgcAF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAcOgcAF\App_KernelDevDebugContainer([
    'container.build_hash' => 'AcOgcAF',
    'container.build_id' => '47256113',
    'container.build_time' => 1653667483,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAcOgcAF');
