<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2uj8RfM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2uj8RfM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2uj8RfM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2uj8RfM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2uj8RfM\App_KernelDevDebugContainer([
    'container.build_hash' => '2uj8RfM',
    'container.build_id' => '23d990fa',
    'container.build_time' => 1654542382,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2uj8RfM');
